AMW-274 lange-demo GitHub action CI fix
ansible-middleware/3trains-cluster-demo pull request #55
Opened 2024-07-17 16:00 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/AMW-274

2024-07-17 16:09 UTC, RanabirChakraborty commented
@rpelisse Please review the PR.

2024-07-23 14:48 UTC, rpelisse requested changes
A few misc changes, but it look good.

Please run manually ansible-lint, I think there is a few more things it will report you can fix!

2024-07-23 14:48 UTC, rpelisse commented on molecule/default/molecule.yml
> +    ANSIBLE_VERBOSITY: 3
Please remove, that for debugging purpose :)

BTW, you can just add Env Var to the build with the same name (ANSIBLE_VERBOSITY) and normally Ansible will use it. (Unless I'm wrong, Ansible always checks if this Env Var is defined, when it starts running).

2024-07-23 14:48 UTC, rpelisse commented on molecule/default/prepare.yml
>          use_backend: dnf
I'm curious.. Why using "backend dnf" instrad of directly ansible.builtin.dnf ? And btw, the ansible.builtin is missing here :)

2024-07-23 14:48 UTC, rpelisse commented on roles/flange_jbcs/tasks/prereqs.yml
> +  become: yes
ansible.builtin missing! :)

2024-07-23 14:48 UTC, rpelisse commented on roles/flange_wildfly/tasks/fine-tuned-wildfly.yml
> +
Please remove those whitespaces!

2024-07-23 14:48 UTC, rpelisse commented on roles/flange_wildfly/tasks/prereqs.yml
> +  pip:
ansible.builtin.pip

2024-07-23 15:30 UTC, RanabirChakraborty commented
@rpelisse Fixed it now! please review it once.

2024-07-24 09:38 UTC, rpelisse requested changes
Just two changes to do and we're good to go!

2024-07-24 09:38 UTC, rpelisse commented on roles/flange_jbcs/tasks/install-jb-httpd.yml
> +  middleware_automation.redhat_csp_download:
@RanabirChakraborty Can you update this to use the new API?

2024-07-24 09:38 UTC, rpelisse commented on roles/flange_jbcs/tasks/main.yml
> +- ansible.builtin.include_tasks:
It's a bit of nick picking, but I would prefer we use this syntax: `ansible.builtin.include_tasks: install.yml`

2024-07-24 09:38 UTC, rpelisse commented on roles/flange_jbcs/tasks/install-jb-httpd.yml
> +  middleware_automation.redhat_csp_download:
Actually, I think you can nuke this. It should not be called anymore. When you will have generated the downstream version of the demo, this will be done, behind the scene, by the downstream collections.

2024-07-24 15:27 UTC, RanabirChakraborty commented
@rpelisse please review now :)

2024-07-25 05:55 UTC, rpelisse approved these changes

2024-07-25 05:55 UTC, merged